
#' Update Check Type selector drop down
#'
#' @param dat_list the list with relevant dataframes for the module
#' @param ck_str the abbreviated string of the module to be used to reference the input field
#'
#' @returns will update the existing check type input field for the module of interest
#'          with the available check types based on the data
#'
update_type_input <- function(dat_list,
                              ck_str){

  check_vec <- c()

  ## SS EXP CS
  if(!is.null(dat_list$ss_exp_cs)){
    for(i in 1:length(dat_list$ss_exp_cs)){
      fl <- gsub('.csv', '', names(dat_list$ss_exp_cs)[i])
      check_vec <- check_vec %>%
        append(paste0('Single Site, Exploratory, Cross-Sectional (', fl, ')'))
    }
  }

  ## MS EXP CS
  if(!is.null(dat_list$ms_exp_cs)){
    for(i in 1:length(dat_list$ms_exp_cs)){
      fl <- gsub('.csv', '', names(dat_list$ms_exp_cs)[i])
      check_vec <- check_vec %>%
        append(paste0('Multi Site, Exploratory, Cross-Sectional (', fl, ')'))
    }
  }

  ## SS ANOM CS
  if(!is.null(dat_list$ss_anom_cs)){
    for(i in 1:length(dat_list$ss_anom_cs)){
      fl <- gsub('.csv', '', names(dat_list$ss_anom_cs)[i])
      check_vec <- check_vec %>%
        append(paste0('Single Site, Anomaly Detection, Cross-Sectional (', fl, ')'))
    }
  }

  ## MS ANOM CS
  if(!is.null(dat_list$ms_anom_cs)){
    for(i in 1:length(dat_list$ms_anom_cs)){
      fl <- gsub('.csv', '', names(dat_list$ms_anom_cs)[i])
      check_vec <- check_vec %>%
        append(paste0('Multi Site, Anomaly Detection, Cross-Sectional (', fl, ')'))
    }
  }

  ## SS EXP LA
  if(!is.null(dat_list$ss_exp_la)){
    for(i in 1:length(dat_list$ss_exp_la)){
      fl <- gsub('.csv', '', names(dat_list$ss_exp_la)[i])
      check_vec <- check_vec %>%
        append(paste0('Single Site, Exploratory, Longitudinal (', fl, ')'))
    }
  }

  ## MS EXP LS
  if(!is.null(dat_list$ms_exp_la)){
    for(i in 1:length(dat_list$ms_exp_la)){
      fl <- gsub('.csv', '', names(dat_list$ms_exp_la)[i])
      check_vec <- check_vec %>%
        append(paste0('Multi Site, Exploratory, Longitudinal (', fl, ')'))
    }
  }

  ## SS ANOM LA
  if(!is.null(dat_list$ss_anom_la)){
    for(i in 1:length(dat_list$ss_anom_la)){
      fl <- gsub('.csv', '', names(dat_list$ss_anom_la)[i])
      check_vec <- check_vec %>%
        append(paste0('Single Site, Anomaly Detection, Longitudinal (', fl, ')'))
    }
  }

  ## MS ANOM LA
  if(!is.null(dat_list$ms_anom_la)){
    for(i in 1:length(dat_list$ms_anom_la)){
      fl <- gsub('.csv', '', names(dat_list$ms_anom_la)[i])
      check_vec <- check_vec %>%
        append(paste0('Multi Site, Anomaly Detection, Longitudinal (', fl, ')'))
    }
  }

  updateSelectInput(inputId = str_c(ck_str, '_type'),
                    choices = check_vec,
                    selected = check_vec[1])
}


#' Load data + filter data for processing
#'
#' @param dat_list the list with relevant dataframes for the module
#' @param input app-level input
#' @param type_input the name of the check type input field for the module
#'
#' @returns the correct dataframe based on the selected check type for the module of interest
#'
load_check_data <- function(dat_list,
                            input,
                            type_input){

  base_type <- stringr::str_remove(input[[type_input]], ' \\(.*')
  file_nm <- stringr::str_extract(input[[type_input]], '(?<=\\()[^)]+(?=\\))')
  file_nm <- paste0(file_nm, '.csv')

  if(base_type == 'Single Site, Exploratory, Cross-Sectional'){
    dat_list$ss_exp_cs[[file_nm]]
  }else if(base_type == 'Single Site, Anomaly Detection, Cross-Sectional'){
    dat_list$ss_anom_cs[[file_nm]]
  }else if(base_type == 'Single Site, Exploratory, Longitudinal'){
    dat_list$ss_exp_la[[file_nm]]
  }else if(base_type == 'Single Site, Anomaly Detection, Longitudinal'){
    dat_list$ss_anom_la[[file_nm]]
  }else if(base_type == 'Multi Site, Exploratory, Cross-Sectional'){
    dat_list$ms_exp_cs[[file_nm]]
  }else if(base_type == 'Multi Site, Anomaly Detection, Cross-Sectional'){
    dat_list$ms_anom_cs[[file_nm]]
  }else if(base_type == 'Multi Site, Exploratory, Longitudinal'){
    dat_list$ms_exp_la[[file_nm]]
  }else if(base_type == 'Multi Site, Anomaly Detection, Longitudinal'){
    dat_list$ms_anom_la[[file_nm]]
  }
}


#' Select appropriate engine & render plot
#'
#' @param plt_rctv the reactive plot object generated by a SQUBA *_output function
#' @param n_plt the N of the plot being generated server side (1, 2, or 3)
#'
#' @returns the rendered plot based on the procedurally selected engine
#'
plt_engine_selector <- function(plt_rctv,
                                n_plt){

  if(n_plt == 1){
    if(any(class(plt_rctv) == 'list') && !any(class(plt_rctv) %in% 'gt_tbl')){
      plt <- plt_rctv[[1]]
    }else{
      plt <- plt_rctv
    }
  }else{
    if(any(class(plt_rctv) == 'list') && !any(class(plt_rctv) %in% 'gt_tbl')){
      if(length(plt_rctv) >= n_plt){
        plt <- plt_rctv[[n_plt]]
      }else{plt <- NULL}
    }else{
      plt <- NULL
    }
  }

  if(!is.null(plt)){
    if(is.null(plt$metadata$pkg_backend)){
      if(any(class(plt) %in% 'gt_tbl')){
        gt::render_gt(plt)
      }else{NULL}
    }else if(plt$metadata$pkg_backend == 'plotly'){
      plotly::renderPlotly(plt)
    }else if(plt$metadata$pkg_backend == 'ggiraph'){
      ggiraph::renderGirafe({ggiraph::girafe(ggobj = plt,
                                             width_svg = 11,
                                             height_svg = 8)})
    }
  }else{
    NULL
  }
}



render_update_notes <- function(notes_rctval,
                                id,
                                mod_name,
                                other_inps,
                                input){

  type_inp <- paste0(id, '_type')
  note_inp <- paste0(id, '_note')
  ss_inp <- paste0(id, '_site_s')
  ms_inp <- paste0(id, '_site_m')
  time_inc_inp <- paste0(id, '_time')

  if(is.null(input[[time_inc_inp]])){
    time_inc_inp <- NA_character_
  }else{
    time_inc_inp <- input[[time_inc_inp]]
  }

  if(grepl('Multi', input[[type_inp]]) & input[['largen']]){
    site_str <- paste0(input[[ms_inp]], collapse = ', ')
  }else if(grepl('Single', input[[type_inp]]) |
           (grepl('Multi', input[[type_inp]]) & !input[['largen']])){
    site_str <- input[[ss_inp]]
  }else{
    site_str <- NA_character_
  }

  new_note <- dplyr::tibble(date = format(Sys.Date(), "%m/%d/%y"),
                     time = format(Sys.time(), "%H:%M:%S"),
                     module = mod_name,
                     check = input[[type_inp]],
                     large_n = ifelse(grepl('Single', input[[type_inp]]), FALSE, input[['largen']]),
                     site = site_str,
                     time_period = time_inc_inp,
                     other_input = other_inps,
                     notes = input[[note_inp]])


  updated_tbl <- notes_rctval %>%
    dplyr::union(new_note) %>% dplyr::filter(module != 'Sample Module')

  return(updated_tbl)

}


plot_downloader <- function(plt_obj,
                            id){

    downloadHandler(
      filename = paste0(id, "_plots.zip"),
      content = function(file) {
        # Handler for single plots
        if (inherits(plt_obj(), "gg") || inherits(plt_obj(), "gt_tbl")) {
          plt_obj <- list(plt_obj())
        }else{
          plt_obj <- plt_obj()
        }

        # Save each plot to a temp file
        tmp_dir <- tempdir()
        plot_files <- character(length(plt_obj))

        # Choose correct save mechanism
        for (i in seq_along(plt_obj)) {
          if(any(class(plt_obj[[i]]) %in% 'gt_tbl')){
            path <- file.path(tmp_dir, paste0(id, "_table_", i, ".rtf"))
            gtsave(plt_obj[[i]], path)
          }else{
            path <- file.path(tmp_dir, paste0(id, "_plot_", i, ".png"))
            ggsave(path, plot = plt_obj[[i]], width = 8, height = 6)
          }
          plot_files[i] <- path
        }

        # Zip them all together
        utils::zip(file, plot_files, flags = "-j")
      },
      contentType = "application/zip"
    )
  }
